import { ValueOf } from "next/dist/shared/lib/constants";

export const API_PATHS = {
  NEWS: "/landingpage",
  STATISTICS: "/statistics",
  GOALS: "/goals",
  COLLEGES: "/colleges",
  RANKINGS: "/classification",
  E_SERVICES: "/service",
  CONTACT: "/contacts",
  LATEST_NEWS: "/latestnews",
};

export const sharedPageNames = {
  infrastructure: "infrastructure",
  halls: "halls",
  laboratories: "laboratories",
  "green areas": "green areas",
  "university life": "university life",
  "promotions form": "promotions form",
  guides: "guides",
  "organizing promotion transactions": "organizing promotion transactions",
  scientificJournals: "scientificJournals",
  practicalAndIntellectualOutput: "practicalAndIntellectualOutput",
  "teachers research": "teachers research",
  "authored books": "authored books",
  "scientific articles": "scientific articles",
  "quality and performance": "quality and performance",
  scopus: "scopus",
  scientificResearcher: "scientificResearcher",
  scientificResearchPortal: "scientificResearchPortal",
  "scientific activities": "scientific activities",
  seminars: "seminars",
  workshops: "workshops",
  courses: "courses",
  forums: "forums",
  admissionAndRegistration: "admissionAndRegistration",
  registrationTerms: "registrationTerms",
  registrationMechanism: "registrationMechanism",
  tuitionFees: "tuitionFees",
  discountsAndScholarships: "discountsAndScholarships",
  patents: "patents",
  universityCalendar: "universityCalendar",
  examInstructions: "examInstructions",
  studentDisciplineInstructions: "studentDisciplineInstructions",
  studentGuidelines: "studentGuidelines",
  topStudents: "topStudents",
  examSchedules: "examSchedules",
  studentActivities: "studentActivities",
  studentTeams: "studentTeams",
  ashurbanipalLibrary: "ashurbanipalLibrary",
  continuingEducationCenter: "continuingEducationCenter",
  urukCulturalCenter: "urukCulturalCenter",
  fitnessCenter: "fitnessCenter",
  gilgameshTheater: "gilgameshTheater",
  celebrationHallsAridoun: "celebrationHallsAridoun",
  olympicSwimmingpool: "olympicSwimmingpool",
  fiveasidePitches: "fiveasidePitches",
  trainingHalls: "trainingHalls",
  dentalClinics: "dentalClinics",
  cloningLibrary: "cloningLibrary",
  cafeteria: "cafeteria",
  graduates: "graduates",
  rehabilitationAndEmployment: "rehabilitationAndEmployment",
  consultingClinics: "consultingClinics",
  electronicInquiriesMinistryHigherEducation:
    "electronicInquiriesMinistryHigherEducation",
  sustainability: "sustainability",
};

export type SharedPage = (typeof sharedPageNames)[keyof typeof sharedPageNames];
